---
- hosts: all
  gather_facts: true
  become: true
  roles:
    - role: devbox_role
  tags:
    - devbox

- hosts: all
  become: false
  gather_facts: true
  roles:
    - role: ansible-role-zsh
    - { role: ansible-role-p10k, zsh_plugin: ohmyzsh }
  tags:
    - common
